export const moduleConfig = {
  colaboradores: {
    title: 'Colaboradores',
    singular: 'colaborador',
    createTitle: 'Novo colaborador',
    listTitle: 'Colaboradores cadastrados',
    eyebrow: 'EQUIPE E ATENDIMENTO',
    description: 'Mantenha os dados da equipe que acolhe e acompanha as famílias.',
    icon: 'UsersRound',
    apiPath: '/colaboradores',
    idField: 'id_pessoa',
    list: true,
    detail: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'nome', label: 'Nome completo', required: true },
      { name: 'cpf', label: 'CPF', required: true },
      { name: 'matricula', label: 'Matrícula', required: true },
      { name: 'telefone', label: 'Telefone', type: 'tel' },
      { name: 'email', label: 'E-mail', type: 'email' },
      { name: 'endereco', label: 'Endereço' },
      {
        name: 'cargo',
        label: 'Cargo',
        type: 'select',
        required: true,
        placeholder: 'Selecione um cargo',
        options: [
          'Administrador(a)',
          'Assistente social',
          'Auxiliar administrativo(a)',
          'Coordenador(a)',
          'Educador(a) social',
          'Psicólogo(a)',
          'Recepcionista',
          'Outro',
        ],
      },
      { name: 'data_admissao', label: 'Data de admissão', type: 'date', required: true },
    ],
    columns: [
      { key: 'nome', label: 'Nome' },
      { key: 'id_pessoa', label: 'ID de cadastro' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'matricula', label: 'Matrícula' },
      { key: 'telefone', label: 'Telefone' },
      { key: 'data_admissao', label: 'Admissão', type: 'date' },
    ],
  },
  doacoes: {
    title: 'Doações',
    singular: 'doação',
    createTitle: 'Nova doação',
    listTitle: 'Doações recebidas',
    eyebrow: 'GESTOS DE SOLIDARIEDADE',
    description: 'Registre as doações recebidas e acompanhe os itens que entram no estoque.',
    icon: 'HandHeart',
    apiPath: '/doacoes',
    idField: 'id_doacao',
    list: true,
    detail: true,
    editable: false,
    deletable: true,
    withItems: true,
    fields: [
      { name: 'data_doacao', label: 'Data da doação', type: 'date', required: true },
      {
        name: 'id_funcionario',
        label: 'Colaborador responsável',
        type: 'resource-select',
        optionsApiPath: '/colaboradores',
        optionValue: 'id_pessoa',
        optionLabel: 'nome',
        required: true,
      },
    ],
    columns: [
      { key: 'id_doacao', label: 'Nº' },
      { key: 'data_doacao', label: 'Data', type: 'date' },
      { key: 'nome_funcionario', label: 'Colaborador responsável' },
      { key: 'itens', label: 'Itens', type: 'items' },
    ],
  },
  estoque: {
    title: 'Estoque',
    singular: 'movimentação',
    eyebrow: 'ENTRADAS E SAÍDAS',
    description: 'Registre entradas e retiradas para manter as quantidades atualizadas.',
    icon: 'ArrowLeftRight',
    mode: 'stock',
  },
  fila: {
    navKey: 'fila',
    title: 'Fila de prioridade',
    singular: 'posição na fila',
    createTitle: 'Adicionar gestante à fila',
    listTitle: 'Fila de prioridade',
    eyebrow: 'ACOMPANHAMENTO PRIORITÁRIO',
    description: 'Organize as posições e acompanhe as gestantes priorizadas pelo atendimento.',
    icon: 'ListOrdered',
    apiPath: '/fila-prioridade',
    idField: 'id_fila',
    list: true,
    detail: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'posicao_fila', label: 'Posição na fila', type: 'number', min: 1, required: true },
      { name: 'data_calculo', label: 'Data do cálculo', type: 'date', required: true },
      { name: 'id_gestante', label: 'ID da gestante', type: 'number', min: 1, required: true },
    ],
    editFields: [
      { name: 'posicao_fila', label: 'Posição na fila', type: 'number', min: 1, required: true },
      { name: 'data_calculo', label: 'Data do cálculo', type: 'date', required: true },
    ],
    columns: [
      { key: 'posicao_fila', label: 'Posição' },
      { key: 'nome_gestante', label: 'Gestante' },
      { key: 'grau_vulnerabilidade', label: 'Vulnerabilidade' },
      { key: 'data_calculo', label: 'Atualizada em', type: 'date' },
    ],
  },
  kits: {
    title: 'Kits maternidade',
    singular: 'kit',
    createTitle: 'Novo kit',
    listTitle: 'Kits cadastrados',
    eyebrow: 'PREPARO E ENTREGA',
    description: 'Monte kits com os itens disponíveis e acompanhe a entrega às gestantes.',
    icon: 'Gift',
    apiPath: '/kits',
    idField: 'id_kit',
    list: true,
    detail: true,
    editable: true,
    deletable: true,
    withItems: true,
    fields: [
      { name: 'status', label: 'Status do kit', required: true },
      { name: 'data_montagem', label: 'Data de montagem', type: 'date' },
      { name: 'data_entrega', label: 'Data de entrega', type: 'date' },
      { name: 'id_gestante', label: 'ID da gestante', type: 'number', min: 1, required: true },
      { name: 'id_funcionario', label: 'ID do colaborador', type: 'number', min: 1, required: true },
    ],
    editFields: [
      { name: 'status', label: 'Status do kit', required: true },
      { name: 'data_entrega', label: 'Data de entrega', type: 'date' },
    ],
    columns: [
      { key: 'id_kit', label: 'Nº' },
      { key: 'nome_gestante', label: 'Gestante' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'data_montagem', label: 'Montagem', type: 'date' },
      { key: 'data_entrega', label: 'Entrega', type: 'date' },
    ],
  },
  triagem: {
    navKey: 'triagem',
    title: 'Triagens sociais',
    singular: 'triagem',
    createTitle: 'Nova triagem',
    listTitle: 'Triagens cadastradas',
    eyebrow: 'ESCUTA E ACOMPANHAMENTO',
    description: 'Registre avaliações sociais e acompanhe as necessidades identificadas.',
    icon: 'ClipboardCheck',
    apiPath: '/triagens',
    idField: 'id_triagem',
    list: true,
    detail: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'data_triagem', label: 'Data da triagem', type: 'date', required: true },
      { name: 'nota_vulnerabilidade', label: 'Nota de vulnerabilidade (1 a 5)', type: 'number', min: 1, max: 5, required: true },
      { name: 'id_gestante', label: 'ID da gestante', type: 'number', min: 1, required: true },
      { name: 'id_funcionario', label: 'ID do colaborador', type: 'number', min: 1, required: true },
      { name: 'observacoes', label: 'Observações', type: 'textarea' },
    ],
    columns: [
      { key: 'data_triagem', label: 'Data', type: 'date' },
      { key: 'nome_gestante', label: 'Gestante' },
      { key: 'nota_vulnerabilidade', label: 'Vulnerabilidade' },
      { key: 'id_funcionario', label: 'Colaborador' },
    ],
  },
};

export const moduleRoutes = [
  { key: 'colaboradores', href: '/colaboradores' },
  { key: 'doacoes', href: '/doacoes' },
  { key: 'estoque', href: '/estoque' },
  { key: 'fila', href: '/fila-prioridade' },
  { key: 'kits', href: '/kits' },
  { key: 'triagem', href: '/triagem' },
];